trigger:
- master

jobs:

- job: Install
  strategy:
    matrix:
      macCatalina:
        imageName: 'macOS-10.15' 
  pool:
    vmImage: $(imageName)
  steps:
  - script: |
      sh install.sh
    displayName: 'Install'