trigger:
- master

jobs:

- job: Install
  strategy:
    matrix:
      macCatalina:
        imageName: 'macOS-10.15' 
  pool:
    vmImage: $(imageName)
  steps:
  - script: |
      brew install tmux
    displayName: 'Before Install'
  - script: |
      ls -la
      zsh ./install.sh
    displayName: 'Install'